B 13 refactoring change order status
Brutt/PhotoStudio pull request #105
Opened 2020-03-23 11:29 UTC by Yuliia-Sh

1) Added enums: ChangeOrderStatusError, EmailTemplate, PhotoStatus
2) order.html - buttons are showed when order already created

2020-03-23 12:01 UTC, Rooman requested changes

2020-03-23 12:01 UTC, Rooman commented on src/main/java/com/photostudio/entity/photo/PhotoStatus.java
> +        return Arrays.stream(PhotoStatus.values())
Разобралась со стримами? 
Крутая. Респект

2020-03-23 12:01 UTC, Rooman commented on src/main/java/com/photostudio/exception/ChangeOrderStatusInvalidException.java
> +        log.error(this.message);
не логируем в самих ексепшенах

2020-03-23 12:01 UTC, Rooman commented on src/main/java/com/photostudio/exception/ChangeOrderStatusInvalidException.java
> +    public ChangeOrderStatusInvalidException(ChangeOrderStatusError error) {
ChangeOrderStatusError переименовать в ErrorType. На Error заканчиваются наследники Error

2020-03-23 12:01 UTC, Rooman commented on src/main/java/com/photostudio/exception/entity/ChangeOrderStatusError.java
> +@Getter
@AllArgsContructor

2020-03-23 12:01 UTC, Rooman commented on src/main/java/com/photostudio/service/impl/DefaultOrderStatusService.java
> +        int id = getOrderStatusIdByStatusName(orderStatus);
вместо вот этого водевиля, было бы лучше если бы был метод в OrderStatus
OrderStatus getNextStatus(OrderStatus)
OrderStatus getPrevStatus(OrderStatus)

2020-03-23 12:01 UTC, Rooman commented on src/test/java/com/photostudio/service/impl/DefaultOrderServiceITest.java
> +        orderService = new DefaultOrderService(jdbcOrderDao, null, orderStatusService, mailService);
почему налл вернулся?

2020-03-23 12:01 UTC, Rooman commented on src/main/java/com/photostudio/service/impl/DefaultOrderService.java
> +    private boolean checkPhoto(int orderId, OrderStatus newOrderStatus) {
тест на метод

2020-03-23 12:01 UTC, Rooman commented on src/main/java/com/photostudio/service/impl/DefaultOrderService.java
>      private boolean checkByDBStatusForward(OrderStatus statusDB, UserRole userRole) {
тест на метод

2020-03-23 12:01 UTC, Rooman commented on src/main/java/com/photostudio/service/impl/DefaultMailService.java
> +    public void sendOnChangeStatus(User user, int orderId, OrderStatus orderStatus) {
тест на метод

2020-03-23 12:08 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/exception/ChangeOrderStatusInvalidException.java
> +        log.error(this.message);
Почему? получается, что только этот класс знает текст сообщения

2020-03-23 13:11 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/exception/ChangeOrderStatusInvalidException.java
> +    public ChangeOrderStatusInvalidException(ChangeOrderStatusError error) {
сделала

2020-03-23 13:12 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/entity/photo/PhotoStatus.java
> +        return Arrays.stream(PhotoStatus.values())
взяла из OrderStatus

2020-03-23 13:15 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/exception/entity/ChangeOrderStatusError.java
> +@Getter
добавила

2020-03-23 13:19 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/exception/ChangeOrderStatusInvalidException.java
> +        log.error(this.message);
убрала

2020-03-23 13:24 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/service/impl/DefaultOrderStatusService.java
> +        int id = getOrderStatusIdByStatusName(orderStatus);
на последовательность в enum нельзя ж полагаться?

2020-03-23 13:25 UTC, Yuliia-Sh commented on src/test/java/com/photostudio/service/impl/DefaultOrderServiceITest.java
> +        orderService = new DefaultOrderService(jdbcOrderDao, null, orderStatusService, mailService);
убрала

2020-03-24 14:03 UTC, Rooman approved these changes

2020-03-24 15:06 UTC, OleksandrGubariev approved these changes

2020-03-24 16:49 UTC, Brutt approved these changes

2020-03-24 19:47 UTC, merged