B 26 3 disable thymeleaf logs at startup
Brutt/PhotoStudio pull request #107
Opened 2020-03-24 08:20 UTC by nomarchia

2020-03-24 08:45 UTC, Brutt commented
Why did you change pom.xml?

2020-03-24 09:14 UTC, nomarchia commented
> Why did you change pom.xml?

I accidentally pushed new changes in pom.xml from the second branch to this branch. I can remove it from here if needed. But anyway same changes would be added after second branch merged into develop,

2020-03-24 09:56 UTC, Miari commented
I understund, that jetty part is from other PR, but as it is here I would like to ask why version 9.4.26 is used? Version 9.4.27 is already available

2020-03-24 10:46 UTC, Brutt commented
> > Why did you change pom.xml?
> 
> I accidentally pushed new changes in pom.xml from the second branch to this branch. I can remove it from here if needed. But anyway same changes would be added after second branch merged into develop,

Push changes related to branch goal only.

2020-03-24 11:54 UTC, ValentynaBondarenko submitted a review, later dismissed

2020-03-24 11:57 UTC, Rooman requested changes

2020-03-24 11:57 UTC, Rooman commented on src/main/resources/logback.xml
> +   <logger name="org.thymeleaf.TemplateEngine" level="OFF"/>
Зачем выключать полностью логи тимлифа?

2020-03-25 17:00 UTC, Yuliia-Sh submitted a review, later dismissed

2020-03-26 06:59 UTC, nomarchia commented on src/main/resources/logback.xml
> +   <logger name="org.thymeleaf.TemplateEngine" level="OFF"/>
Исправлено

2020-03-26 07:03 UTC, nomarchia commented
> Push changes related to branch goal only.

Sure, of course. That's was my mistake. But since those jetty pom.xml changes already merged to develop branch, do we need to remove it from tcurrenthis branch now? Anyway, it's the same as in the develop branch.

2020-03-26 07:15 UTC, nomarchia commented
> I understund, that jetty part is from other PR, but as it is here I would like to ask why version 9.4.26 is used? Version 9.4.27 is already available

By some reason 9.4.27 wasn't available in my Idea, Maven was not finding it. That's why I tried to use 9.2.46

2020-03-26 08:38 UTC, OleksandrGubariev submitted a review, later dismissed

2020-03-26 09:41 UTC, Yuliia-Sh submitted a review, later dismissed

2020-03-26 10:18 UTC, shaguahill approved these changes

2020-03-26 10:19 UTC, OleksandrGubariev approved these changes

2020-03-26 11:34 UTC, Rooman approved these changes

2020-03-26 13:03 UTC, merged