[b-26-5] Add tests for Security (TO-DO mark)
Brutt/PhotoStudio pull request #109
Opened 2020-03-24 10:37 UTC by ValentynaBondarenko

2020-03-24 19:44 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/web/filter/SecurityFilter.java
> +    }
Если это только для тестов используется, то почему модификатор доступа public?

2020-03-24 20:55 UTC, ValentynaBondarenko commented on src/main/java/com/photostudio/web/filter/SecurityFilter.java
> +    }
виправила

2020-03-24 21:01 UTC, Rooman requested changes

2020-03-24 21:01 UTC, Rooman commented on src/test/java/com/photostudio/web/filter/SecurityFilterTest.java
> +        when(securityServiceMock.getSession(any())).thenReturn(session);
Этот код дублируется. Можем вынести его в отдельный метод например
void mockCurrentUser(UserRole role) 
?

2020-03-24 21:11 UTC, ValentynaBondarenko commented on src/test/java/com/photostudio/web/filter/SecurityFilterTest.java
> +        when(securityServiceMock.getSession(any())).thenReturn(session);
виправила

2020-03-24 21:12 UTC, Rooman approved these changes
аффтор жги еще

2020-03-24 23:36 UTC, OleksandrGubariev approved these changes

2020-03-25 07:50 UTC, shaguahill approved these changes

2020-03-25 09:17 UTC, merged