[b-26-6] & [b-26-7]
Brutt/PhotoStudio pull request #111
Opened 2020-03-24 19:00 UTC by shaguahill

Added to PropertyReader read develop.application.properties (with higher level then application.properties)
Added mail.properties to application.properties and removed mail.properties
Changed MailSender for fork with application.properties

This task required a task [b-26-7] , then:
Renamed getAllProperties to readProperties and set private
Added public method getProperties

2020-03-24 19:12 UTC, Rooman requested changes
все остальное хорошо

2020-03-24 19:12 UTC, Rooman commented on .gitignore
> +src/main/resources/develop.application.properties
предлагаю просто написать dev.application.properties
1. Такое имя часто используется
2. Нам не важно где лежит этот файл. В ресурсах мейн или тестовых

2020-03-24 19:12 UTC, Rooman commented on src/main/java/com/photostudio/util/PropertyReader.java
> +        return new Properties(properties);
Почему мы создаем копию?

2020-03-24 19:24 UTC, shaguahill commented on .gitignore
> +src/main/resources/develop.application.properties
Изменил

2020-03-24 19:28 UTC, shaguahill commented on src/main/java/com/photostudio/util/PropertyReader.java
> +        return new Properties(properties);
Если кто-то внесет изменения в пропертя, то они будут в копиии. А исходные пропертя останутся  как были, и остальной функционал останется рабочим.

2020-03-24 19:59 UTC, Rooman submitted a review, later dismissed

2020-03-24 20:56 UTC, ValentynaBondarenko approved these changes

2020-03-25 08:53 UTC, Brutt approved these changes

2020-03-25 09:25 UTC, OleksandrGubariev approved these changes

2020-03-25 09:26 UTC, merged