B-37 forgot password
Brutt/PhotoStudio pull request #129
Opened 2020-04-04 13:49 UTC by shaguahill

1.Created ResetPasswordServlet
2.Added reset-password page and link to this page from login page
3.Added language properties to reset-password page
4.Changed scripts V1_12, V1_13 for DB witch didn`t understand h2 db
5. Added cache for messages about password and mapper for it
6. Added table to db PasswordEmailTemplate
7. added enum MessageType for email types and entity PasswordEmailTemplate
8. Added method resetUserPassword and moved method change password to Security folder
9. Added method sendNewPassword to MailService
10. Added languages properties for change-password page
11. Added tests for EmailTemplateCachedDao for ResetPassword

Bug fix [def-19]:
1. Created method changePassword in UserDao
2. Changed logic for method changeUserPassword and ChangePasswordServlet

2020-04-04 14:10 UTC, Rooman commented on src/main/java/com/photostudio/dao/jdbc/JdbcEmailTemplateCachedDao.java
> +            passwordEmailTemplateCache = new ArrayList<>();
1. Плохая идея ассайнить пустую коллекцию. Может быть обращение к пустой из другого потока
2. volatile

2020-04-04 14:11 UTC, Rooman commented on src/main/java/com/photostudio/dao/jdbc/JdbcEmailTemplateCachedDao.java
> +        if (optionalPasswordEmailTemplate.isPresent()) {
if(validate) {
   throw exception
}

normal logic

2020-04-04 14:12 UTC, Rooman commented on src/main/java/com/photostudio/entity/email/MessageType.java
> +        return messageId;
lombok/

2020-04-04 14:12 UTC, Rooman commented on src/main/java/com/photostudio/entity/email/MessageType.java
> +
bez perenosov strok nikyda

2020-04-04 14:13 UTC, Rooman commented on src/main/java/com/photostudio/entity/email/MessageType.java
> +                .orElseThrow(() -> new IllegalArgumentException("MessageTpe name is not correct!"));
a kakoy imenno name ne correct/

2020-04-04 14:13 UTC, Rooman commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
> +        log.info("Started service reset password for user with id " + user.getId());
-

2020-04-04 14:14 UTC, Rooman commented on src/main/java/com/photostudio/service/impl/DefaultMailService.java
> +                .replace("<password>", password), user.getEmail());
:+1:

2020-04-04 14:16 UTC, Rooman commented on src/main/java/com/photostudio/web/servlet/security/ResetPasswordServlet.java
> +        User user = userService.getUserByEmail(email);
1 method v servlete = 1 vuzov metoda service. 
servlet ne yavlyaetya dispatcherom. logica dolgna but v service

2020-04-04 14:17 UTC, Rooman commented on src/main/webapp/assets/css/reset-password.css
> +    border-color: #FCC5D9 !important;
ваши стили очень важны для нас...

2020-04-04 15:39 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/dao/jdbc/JdbcEmailTemplateCachedDao.java
> +        if (optionalPasswordEmailTemplate.isPresent()) {
тут можна один filter использовать

2020-04-04 15:39 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
MailService содержит MailSender, тут точно нужно и то и другое?

2020-04-04 17:49 UTC, shaguahill commented on src/main/java/com/photostudio/dao/jdbc/JdbcEmailTemplateCachedDao.java
> +            passwordEmailTemplateCache = new ArrayList<>();
Fixed. О volatile перечитал.

2020-04-04 17:50 UTC, shaguahill commented on src/main/java/com/photostudio/dao/jdbc/JdbcEmailTemplateCachedDao.java
> +        if (optionalPasswordEmailTemplate.isPresent()) {
Fiexed.
О использовании filter - в курсе. Использовал 2 для читабельности кода.

2020-04-04 17:50 UTC, shaguahill commented on src/main/java/com/photostudio/entity/email/MessageType.java
> +        return messageId;
Добавил

2020-04-04 17:50 UTC, shaguahill commented on src/main/java/com/photostudio/entity/email/MessageType.java
> +
Убрал лишний перенос

2020-04-04 17:50 UTC, shaguahill commented on src/main/java/com/photostudio/entity/email/MessageType.java
> +                .orElseThrow(() -> new IllegalArgumentException("MessageTpe name is not correct!"));
Добавил названия в ошибки

2020-04-04 17:51 UTC, shaguahill commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
> +        log.info("Started service reset password for user with id " + user.getId());
Косяк. Устранил

2020-04-04 17:51 UTC, shaguahill commented on src/main/java/com/photostudio/web/servlet/security/ResetPasswordServlet.java
> +        User user = userService.getUserByEmail(email);
Изменил логику

2020-04-04 17:53 UTC, shaguahill commented on src/main/webapp/assets/css/reset-password.css
> +    border-color: #FCC5D9 !important;
Хотя мой css файл после bootstrap, при active bootstrap имеет выше приоритет. По этому !important (P.S. В курсе что решение не очень)

2020-04-04 17:55 UTC, shaguahill commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
Он нужен для метода register для добавления нового юзера. Когда мы перенесем отправку сообщение для этого случая в MailService - MailSender уберется.

2020-04-04 19:20 UTC, ValentynaBondarenko submitted a review, later dismissed

2020-04-04 19:22 UTC, nomarchia submitted a review, later dismissed

2020-04-04 21:11 UTC, Miari requested changes

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.label.new=Neue Passwort
Neues Passwort

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.title=Ändere das Passwort
Passwort ändern

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password.properties
> +page.title=Photo Studio
Photostudio

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +page.title=Foto Studio
Fotostudio

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.label.repeat.new=Wiederhole das neue Passwort
Neues Passwort wiederholen

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.error.incorrect.old=Das Passwort ist inkorrekt
Das Passwort ist falsch

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password.properties
> +change.password.error.not.match=Password does not match
The password does not match

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.error.not.match=Passwort stimmt nicht überein
Das Passwort stimmt nicht überein

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_en_US.properties.properties
> +page.title=Photo Studio
Photostudio

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_en_US.properties.properties
> +change.password.error.not.match=Password does not match
The password does not match

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_ru.properties.properties
> +change.password.error.not.match=Паролии не совпадают
Пароли не совпадают

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_ru.properties.properties
> +page.title=Фото Студия
Фотостудия

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/change-password_ru.properties.properties
> +change.password.label.repeat.new=Повторить новый пароль
Повторите новый пароль

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/reset-password.properties
> +page.title=Photo Studio
Photostudio

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/reset-password_de.properties
> +reset.password.button=Neues Passwort senden
Fotostudio

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/reset-password_en_US.properties
> +page.title=Photo Studio
Photostudio

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/reset-password_ru.properties
> +page.title=Фото Студия
Фотостудия

2020-04-04 21:11 UTC, Miari commented on src/main/webapp/WEB-INF/templates/reset-password_de.properties
> +reset.password.placeholder=Geben sie ihre E-Mailadresse ein
Geben Sie Ihre E-Mail-Adresse ein

2020-04-04 21:11 UTC, Miari commented on src/test/java/com/photostudio/dao/jdbc/JdbcEmailTemplateCachedDaoTest.java
> +        String expectedSubject = "Miari Fotografie Reset password";
А Subject на немецком мы проверяем где-нибудь?

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.label.new=Neue Passwort
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.title=Ändere das Passwort
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password.properties
> +page.title=Photo Studio
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +page.title=Foto Studio
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.label.repeat.new=Wiederhole das neue Passwort
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.error.incorrect.old=Das Passwort ist inkorrekt
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password.properties
> +change.password.error.not.match=Password does not match
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_de.properties.properties
> +change.password.error.not.match=Passwort stimmt nicht überein
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_en_US.properties.properties
> +page.title=Photo Studio
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_en_US.properties.properties
> +change.password.error.not.match=Password does not match
Fixed

2020-04-05 05:50 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_ru.properties.properties
> +change.password.error.not.match=Паролии не совпадают
Fixed

2020-04-05 05:51 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_ru.properties.properties
> +page.title=Фото Студия
Fixed

2020-04-05 05:51 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/change-password_ru.properties.properties
> +change.password.label.repeat.new=Повторить новый пароль
Fixed

2020-04-05 05:51 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/reset-password.properties
> +page.title=Photo Studio
Fixed

2020-04-05 05:51 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/reset-password_de.properties
> +reset.password.button=Neues Passwort senden
Fixed

2020-04-05 05:51 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/reset-password_en_US.properties
> +page.title=Photo Studio
Fixed

2020-04-05 05:51 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/reset-password_ru.properties
> +page.title=Фото Студия
Fixed

2020-04-05 05:51 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/reset-password_de.properties
> +reset.password.placeholder=Geben sie ihre E-Mailadresse ein
Fixed

2020-04-05 05:52 UTC, shaguahill commented on src/test/java/com/photostudio/dao/jdbc/JdbcEmailTemplateCachedDaoTest.java
> +        String expectedSubject = "Miari Fotografie Reset password";
Subject и body берутся с DB. Файл с накаткой V1_15__add_password_email_templates.sql

2020-04-05 05:56 UTC, OleksandrGubariev approved these changes

2020-04-05 06:09 UTC, ValentynaBondarenko approved these changes

2020-04-05 08:28 UTC, Miari approved these changes

2020-04-05 08:29 UTC, merged

2020-04-05 09:47 UTC, Rooman commented on src/main/webapp/assets/css/reset-password.css
> +    border-color: #FCC5D9 !important;
нужно было поставить более сложный селектор 
ul.items li a.item-link  {}

2020-04-05 09:48 UTC, Rooman commented on src/main/webapp/WEB-INF/templates/change-password_ru.properties.properties
> +change.password.label.repeat.new=Повторить новый пароль
@shaguahill ты каждый раз писал фиксел или копировал и вставлял? )

2020-04-05 09:50 UTC, Rooman commented
красавчик :+1: