F 4 html coding for remaining pages
Brutt/PhotoStudio pull request #132
Opened 2020-04-05 10:42 UTC by nomarchia

Added following new page templates:
Portfolio, Portfolio-newborns, Portfolio-babies;
Price;
Contact;
Data protection, Legal information;

Added multi-lang support for elements of pages;
Added StatisPageServlet for being able to access new pages;
Added these pages to excludedUrls in SecurityFilter;

2020-04-05 10:54 UTC, Yuliia-Sh commented on src/main/webapp/assets/css/portfolio.css
> +
Класс container-main не решает вопрос с футером?

2020-04-05 11:16 UTC, nomarchia commented on src/main/webapp/assets/css/portfolio.css
> +
Это не с футером проблема, а с фоном - он сейчас взят от другой страницы. Это фикс чтобы не было зазора между фоном и футером, там оставалось пикселей 10 белой полосы. После того, как будут нормальные фоны от Лилит, это будет убрано (специально коммент оставил, чтобы самому потом не забыть).

2020-04-05 21:21 UTC, Miari commented
Please do the following changes to the html pages:
* Remove checkbox from the contact form
* Change "Login" to "Anmeldung" in header in german version
* Change "GE" to "DE" in language selection
* Change "Email" to "Емейл" in russion version on login page

2020-04-06 21:45 UTC, Miari requested changes

2020-04-06 21:45 UTC, Miari commented on src/main/java/com/photostudio/web/servlet/ContactFormServlet.java
> +        mailSender.send("New message via contact form", stringBuilder.toString(), "nomarchia2@gmail.com");
Admin's email needed here

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/contact_de.properties
> +message.placeholder=Botschaft
Nachricht

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/contact_de.properties
> +email.placeholder=Email
E-Mail. Email в немецком зубная эмаль ))

и Nachricht вместо Botschaft

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/contact.properties
> +index.placeholder=Index
ZIP

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/contact_de.properties
> +index.placeholder=Index
PLZ

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/contact_en_US.properties
> +index.placeholder=Index
ZIP

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/data-protection_en_US.properties
> +data.title=Data Protection
protection

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/data-protection.properties
> +data.title=Data Protection
protection

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/fragment/footer.html
> +            data protection
Data

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/fragment/footer.html
> +            legal information
Legal

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/legal-information_de.properties
> +legal.title=Rechtsinformation
AGB

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/legal-information.properties
> +legal.title=Legal Information
General Terms and Conditions

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/legal-information_ru.properties
> +legal.title=Правовая информация
Общие положения и условия

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/legal-information_en_US.properties
> +legal.title=Legal Information
General Terms and Conditions

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/legal-information.html
> +                    Legal Information
General Terms and Conditions

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/legal-information.html
> +    <title th:text="#{legal.title}">Legal Info</title>
General Terms and Conditions

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/portfolio-babies_ru.properties
> +portfolio.babies.title=Младенцы
Малыши

2020-04-06 21:45 UTC, Miari commented on src/main/webapp/WEB-INF/templates/portfolio_ru.properties
> +babies.title=Младенцы
Малыши

2020-04-07 04:03 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/web/servlet/ContactFormServlet.java
> +        mailSender.send("New message via contact form", stringBuilder.toString(), "nomarchia2@gmail.com");
есть метод sendToAdmin

2020-04-07 15:17 UTC, nomarchia commented on src/main/java/com/photostudio/web/servlet/ContactFormServlet.java
> +        mailSender.send("New message via contact form", stringBuilder.toString(), "nomarchia2@gmail.com");
Это было временное решение для теста, сейчас там sendToAdmin()

2020-04-07 15:48 UTC, nomarchia commented on src/main/webapp/WEB-INF/templates/contact_de.properties
> +message.placeholder=Botschaft
changed

2020-04-07 15:48 UTC, nomarchia commented on src/main/webapp/WEB-INF/templates/contact_de.properties
> +email.placeholder=Email
changed

2020-04-07 15:48 UTC, nomarchia commented on src/main/webapp/WEB-INF/templates/contact_de.properties
> +index.placeholder=Index
changed

2020-04-07 15:48 UTC, nomarchia commented on src/main/webapp/WEB-INF/templates/contact.properties
> +index.placeholder=Index
changed

2020-04-07 15:48 UTC, nomarchia commented on src/main/webapp/WEB-INF/templates/legal-information_en_US.properties
> +legal.title=Legal Information
changed

2020-04-07 15:48 UTC, nomarchia commented on src/main/webapp/WEB-INF/templates/legal-information.html
> +    <title th:text="#{legal.title}">Legal Info</title>
changed

2020-04-07 15:49 UTC, nomarchia commented on src/main/webapp/WEB-INF/templates/portfolio-babies_ru.properties
> +portfolio.babies.title=Младенцы
поправлено)

2020-04-07 15:49 UTC, nomarchia commented on src/main/webapp/WEB-INF/templates/portfolio_ru.properties
> +babies.title=Младенцы
поправлено)

2020-04-07 16:16 UTC, Miari approved these changes

2020-04-07 16:25 UTC, Yuliia-Sh approved these changes

2020-04-07 16:47 UTC, shaguahill approved these changes

2020-04-07 16:49 UTC, merged