B 15 add new order
Brutt/PhotoStudio pull request #71
Opened 2020-02-27 15:02 UTC by shaguahill

[b-15] Add new Order:

1. Created sql request and method for insert new order to DB
2. Added link /order to html files
3. Added method post for add new order
4. Changed new-order.html
5. Fix bug with get photo from empty list
6. Resolve conflicts
7. Add path to WebServlet after merge from develop

2020-02-27 15:08 UTC, viktorterljuk commented on src/main/java/com/photostudio/dao/jdbc/JdbcOrderDao.java
> +            LOG.info("Order created and added to DB");
add order object to the log message

2020-02-27 15:49 UTC, shaguahill commented on src/main/java/com/photostudio/dao/jdbc/JdbcOrderDao.java
> +            LOG.info("Order created and added to DB");
Fixed

2020-02-28 08:40 UTC, Rooman commented on src/main/java/com/photostudio/web/servlet/order/OrderServlet.java
> +@WebServlet(urlPatterns = {"/order", "/order/*"})
разнести в два сервлета

2020-02-28 08:41 UTC, Rooman commented on src/main/java/com/photostudio/web/servlet/order/OrderServlet.java
> +                    TemplateEngineFactory.process(request, response, "new-order", paramsMap);
мне кажется что если это запрос на GET /order/{id} но это не new order.Это просто order. Название шаблона сбивает.

2020-02-28 16:27 UTC, shaguahill commented on src/main/java/com/photostudio/web/servlet/order/OrderServlet.java
> +@WebServlet(urlPatterns = {"/order", "/order/*"})
Разнес

2020-02-28 16:28 UTC, shaguahill commented on src/main/java/com/photostudio/web/servlet/order/OrderServlet.java
> +                    TemplateEngineFactory.process(request, response, "new-order", paramsMap);
Название изменил

2020-02-28 16:52 UTC, Rooman requested changes
Можно ли в конектсте данной задачи внести изменения по скриптам для базы которые мы обсуждали вчера?

2020-02-28 16:52 UTC, Rooman commented on src/main/java/com/photostudio/dao/jdbc/JdbcOrderDao.java
> +            "(SELECT id FROM OrderStatus WHERE statusName='New'),(SELECT id FROM Users WHERE email=?), ?)";
OrderStatus <- статические данные которые не будут меняться. Мне не нравится что мы делаем вложенный селект. Можешь закешировать эти значения?
Зачем вложенный селект на юзеров? Если у нас есть имейл, почему у нас нету айдишника?

2020-02-28 16:52 UTC, Rooman commented on src/main/java/com/photostudio/web/servlet/order/AddNewOrderServlet.java
> +        Order.OrderBuilder order = Order.builder().orderDate(LocalDateTime.now())
это orderBuilder

2020-02-28 16:52 UTC, Rooman commented on src/main/java/com/photostudio/web/servlet/order/AddNewOrderServlet.java
> +        if (comment.equals("")) {
в три строки пожалуйста этот код

2020-02-28 16:52 UTC, Rooman commented on src/main/java/com/photostudio/web/servlet/order/OrderServlet.java
> +    private String getLastPartOfUri(HttpServletRequest request) {
Если бы ты тестировал этот метод, что стоило бы сделать, то ты бы передавал сюда не request а String uri. 
И название метода getIdFromURI потому что по факту он достает конкретно идишник в твоей конкретной задаче.

2020-02-28 16:52 UTC, Rooman commented on src/main/webapp/WEB-INF/templates/admin-page.html
> +                    <a href="order" class="btn btn-submit btn-outline-dark button">New order</a>
это точно будет работать? Это относительная линка? Не нужно ли делать th:href?

2020-02-28 16:52 UTC, Rooman commented on src/main/webapp/WEB-INF/templates/order.html
> +            <textarea th:if="${order.comment} == null" class="form-control order__detail-info order__comment"
объясни пожалуйста зачем это разбивать на две части. Нельзя ли объеделить и th:text и placehlder

2020-02-28 16:52 UTC, Rooman commented on src/main/webapp/assets/js/order/new-order.js
> +        $.post({
@Brutt Юра, мы используем джаваскрипт или нет?

2020-02-28 17:21 UTC, Brutt commented on src/main/webapp/assets/js/order/new-order.js
> +        $.post({
В нас є деяка частина функціонала на JS, яка стосується юзерів.

2020-02-28 18:04 UTC, Rooman commented on src/main/webapp/assets/js/order/new-order.js
> +        $.post({
@Brutt В данном контексте как поступает? Мы используем JS для нового кода?

2020-02-28 18:32 UTC, Rooman commented on src/main/java/com/photostudio/dao/jdbc/mapper/OrderWithPhotoRowMapper.java
> +            if (source != null) {
меня смущает эта строка... 
Тут точно только так можно написать?

2020-03-02 09:30 UTC, Brutt commented on src/main/webapp/assets/js/order/new-order.js
> +        $.post({
Не використовуємо JS для нового коду

2020-03-02 23:08 UTC, shaguahill commented on src/main/java/com/photostudio/dao/jdbc/JdbcOrderDao.java
> +            "(SELECT id FROM OrderStatus WHERE statusName='New'),(SELECT id FROM Users WHERE email=?), ?)";
Done

2020-03-02 23:09 UTC, shaguahill commented on src/main/java/com/photostudio/web/servlet/order/AddNewOrderServlet.java
> +        Order.OrderBuilder order = Order.builder().orderDate(LocalDateTime.now())
Renamed

2020-03-02 23:09 UTC, shaguahill commented on src/main/java/com/photostudio/web/servlet/order/AddNewOrderServlet.java
> +        if (comment.equals("")) {
Done

2020-03-02 23:09 UTC, shaguahill commented on src/main/java/com/photostudio/web/servlet/order/OrderServlet.java
> +    private String getLastPartOfUri(HttpServletRequest request) {
Done

2020-03-02 23:10 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/admin-page.html
> +                    <a href="order" class="btn btn-submit btn-outline-dark button">New order</a>
Так как у нас пока что запросы на эту страницу идут с корневой папки  - это работает. Но на всякий случай, если что-то поменяется - изменил на th:href

2020-03-02 23:11 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/order.html
> +            <textarea th:if="${order.comment} == null" class="form-control order__detail-info order__comment"
Объединил

2020-03-02 23:12 UTC, shaguahill commented on src/main/webapp/assets/js/order/new-order.js
> +        $.post({
Изменил на form. Но так как вложеных форм не бывает, проблему это не решило.

2020-03-02 23:13 UTC, shaguahill commented on src/main/java/com/photostudio/dao/jdbc/mapper/OrderWithPhotoRowMapper.java
> +            if (source != null) {
Не нашел другого способа. Как будет лучше?

2020-03-03 11:36 UTC, closed without merging