Demo preparation
Brutt/PhotoStudio pull request #77
Opened 2020-03-02 14:51 UTC by Yuliia-Sh

1) changed login page according to design
2) changed links in the navigation fragment - th:href used

2020-03-02 15:33 UTC, viktorterljuk submitted a review, later dismissed

2020-03-02 16:00 UTC, Brutt reviewed
1) З адмін сторінки не працює навігація
2) на адмін сторінці не працює дропдаун меню
3) вигляд логін сторінки не відповідає дизайну (кнопка Sigh in, футер порожній)

2020-03-03 09:52 UTC, ValentynaBondarenko submitted a review, later dismissed

2020-03-03 10:50 UTC, Brutt submitted a review, later dismissed

2020-03-03 13:23 UTC, Rooman requested changes

2020-03-03 13:23 UTC, Rooman commented on src/main/webapp/WEB-INF/templates/fragment/footer.html
> +        <span>data protection</span>
span излишен

2020-03-03 13:23 UTC, Rooman commented on src/main/webapp/WEB-INF/templates/login.html
> +                    <small th:if="${invalid == 'yes'}"  class="form-text incorrect-login">
The <big> element is deprecated in HTML5, but not earlier versions.
<small> </small> tag (not deprecated)
Interestingly, the <small> tag will probably not be deprecated in HTML5, although there is some debate about it.
The small tag is intended to mean, not diminutive appearance, although browsers will display it that way, but rather "small" in the semantic sense, as in the small print.

http://gottheknack.com/a_htmlCss/weeks/week6/e/deprecated/deprecated.html

Говоря русским языком. HTML разметка должна описатывать семантику, а не визуальное отображение. Тут можно применить div с классом.

2020-03-03 13:23 UTC, Rooman commented on src/main/webapp/assets/css/common.css
> +.footer span {
а что если просто .footer {tt:uppercase;} ? 
не нравится применение тегов без классов.

2020-03-03 13:23 UTC, Rooman commented on src/main/webapp/assets/css/login.css
> +       background: #FAE1DE;;
точно все правильно тут? 
Раньше была opacity.

2020-03-03 13:23 UTC, Rooman commented on src/main/webapp/assets/css/login.css
> +.btn:hover {
ты оверрайдишь стиль бутстрапа? 
Можем добавить свой класс button, навесить на него нужные нам стили и добавить его на те кнопки которые мы ъотим переопределить?

2020-03-03 13:32 UTC, Yuliia-Sh commented on src/main/webapp/WEB-INF/templates/fragment/footer.html
> +        <span>data protection</span>
убрала

2020-03-03 13:35 UTC, Yuliia-Sh commented on src/main/webapp/WEB-INF/templates/login.html
> +                    <small th:if="${invalid == 'yes'}"  class="form-text incorrect-login">
заменила, спасибо, буду знать

2020-03-03 13:36 UTC, Yuliia-Sh commented on src/main/webapp/assets/css/common.css
> +.footer span {
так тоже работает

2020-03-03 13:36 UTC, Yuliia-Sh commented on src/main/webapp/assets/css/common.css
> +.footer span {
убрала span и перенесла стиль

2020-03-03 13:37 UTC, Yuliia-Sh commented on src/main/webapp/assets/css/login.css
> +       background: #FAE1DE;;
Вот не знаю, дизайн видимо изменился...

2020-03-03 13:51 UTC, Yuliia-Sh commented on src/main/webapp/assets/css/login.css
> +.btn:hover {
хороший вопрос, в данном случае кнопка одна, все не анализировала

2020-03-03 13:54 UTC, Yuliia-Sh commented on src/main/webapp/assets/css/login.css
> +.btn:hover {
у меня видимо был вопрос - можно ли переопределять стили бутсрапа? я попробовала - технически оказалось можна; поменяла сейчас на .sign-in-button здесь

2020-03-03 14:21 UTC, merged