fix bugs in LocalDiskPhotoDao
Brutt/PhotoStudio pull request #90
Opened 2020-03-18 22:14 UTC by OleksandrGubariev

2020-03-18 22:17 UTC, Rooman commented on src/main/java/com/photostudio/dao/file/LocalDiskPhotoDao.java
> +        File dirOrder = new File(File.separator + path + File.separator + "Order-" + orderId);
оторву руки. 
Или конструктор класса File, или статический метод класса Paths

2020-03-18 22:52 UTC, Miari submitted a review, later dismissed

2020-03-19 00:16 UTC, Rooman requested changes

2020-03-19 00:16 UTC, Rooman commented on src/main/java/com/photostudio/dao/file/LocalDiskPhotoDao.java
> +                    String photoPath = new File(dirOrder, fileName).toString();
нельзя использовать toString для бизнес логики... 
используй другой метод для получения пути 
getAbsolutePath
getCanonicalPath
getPath
getName
etc

2020-03-19 08:48 UTC, ValentynaBondarenko approved these changes

2020-03-19 09:34 UTC, Miari approved these changes

2020-03-19 09:49 UTC, Brutt approved these changes

2020-03-19 11:43 UTC, merged