[def-9] Change color active bread-crumble btn:
Brutt/PhotoStudio pull request #98
Opened 2020-03-20 08:59 UTC by shaguahill

Added opacity to breadcrumb-item and unset it for current page
Added hover to not active buttons
Added few changes to links, using thymeleaf and webContext

2020-03-20 09:11 UTC, Yuliia-Sh commented on src/main/webapp/assets/css/common.css
hover тут недостаточно? для чего еще класс __active?

2020-03-20 09:14 UTC, Yuliia-Sh submitted a review, later dismissed

2020-03-20 09:20 UTC, Miari submitted a review, later dismissed

2020-03-20 09:42 UTC, Rooman requested changes

2020-03-20 09:42 UTC, Rooman commented on src/main/webapp/WEB-INF/templates/all-users.html
> +                <li class="breadcrumb-item"><a th:href="@{/admin}">Admin page</a></li>
А можем зарефакторить этот ужастный кусок?
В списке могут быть только елементы li. 
Тег img мы используем для отображения контента страницы (фото товара, фото юзера). Декоративные имеджы вещаем на CSS. 
Соответсвенно удаляем отсюда img, и делаем стрелки через :after для li.

2020-03-20 16:16 UTC, shaguahill commented on src/main/webapp/WEB-INF/templates/all-users.html
> +                <li class="breadcrumb-item"><a th:href="@{/admin}">Admin page</a></li>
Перенесено в css

2020-03-20 16:28 UTC, Brutt submitted a review, later dismissed

2020-03-20 17:06 UTC, OleksandrGubariev submitted a review, later dismissed

2020-03-21 10:05 UTC, OleksandrGubariev approved these changes

2020-03-23 07:04 UTC, Brutt approved these changes

2020-03-23 08:28 UTC, nomarchia approved these changes

2020-03-24 13:18 UTC, merged