[def-11] Сookies are not cleared after session is expired:
Brutt/PhotoStudio pull request #99
Opened 2020-03-20 11:49 UTC by nomarchia

1) Problem solved, now session is being cleared and user logged out out after expiry time;

2020-03-20 11:57 UTC, OleksandrGubariev approved these changes

2020-03-20 11:59 UTC, Yuliia-Sh approved these changes

2020-03-20 12:49 UTC, Rooman requested changes

2020-03-20 12:49 UTC, Rooman commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
> +                        sessionList.remove(session);
эм... 
А в чем фикс? 
В том что мы удаляли вызывая метод на итераторе, а теперь вызываем метод на листе?
CuncurrentModificationException о чем нибуть говорит?

2020-03-23 10:19 UTC, nomarchia commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
> +                        sessionList.remove(session);
потому что на методе remove() итератора летит:
UnsupportedOperationException - if the remove operation is not supported by this iterator

Я решил заменить его на remove() CopyOnWriteArrayList-а. После этого у меня перестал лететь эксепшн и при экспайре сессии просто выкидывало на страницу логина при попытке попасть на скрытую страницу

2020-03-23 11:38 UTC, Brutt commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
> +                        sessionList.remove(session);
@Rooman Але ж ми використовуємо CopyOnWriteArrayList, що якраз і допомагає усунути CuncurrentModificationException. Ось перший загуглений приклад: https://crunchify.com/copyonwritearraylist-vs-arraylist-in-java-comparison-and-example/

2020-03-23 11:40 UTC, Rooman commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
> +                        sessionList.remove(session);
@nomarchia Ты разобрался почему в CopyOnWriteArrayList незаимплементирован remove на итераторе? Удалять через коллекцию же дольше по времени. 
@ValentynaBondarenko @OleksandrGubariev @Yuliia-Sh @shaguahill поможете разобраться почему работает так?

@ValentynaBondarenko Ты разрабатывала этот функционал. Как получилось что метод который ты использовала никогда не будет работать? Почему не было написано теста, и это не было протестировано?

@nomarchia Почему сейчас нет теста и это не протестировано?

2020-03-23 14:59 UTC, Yuliia-Sh commented on src/main/java/com/photostudio/security/impl/DefaultSecurityService.java
> +                        sessionList.remove(session);
потому что итератор хранит ссылку на массив на тот момент, когда он был создан:"The "snapshot" style iterator method uses a reference to the state of the array at the point that the iterator was created. This array never changes during the lifetime of the iterator, so interference is impossible and the iterator is guaranteed not to throw ConcurrentModificationException. The iterator will not reflect additions, removals, or changes to the list since the iterator was created. Element-changing operations on iterators themselves (remove, set, and add) are not supported. These methods throw UnsupportedOperationException." Это из документации к классу

2020-03-24 10:04 UTC, ValentynaBondarenko approved these changes

2020-03-30 05:58 UTC, closed without merging